"""Journal correctness -- checked before it is trusted with the first real trade.

The handoff table has claimed "tested end-to-end" since session 1; no test file existed.
Written now because forward-recorded trades are the project's only uncontaminated
evidence (handoff §8) -- a silent arithmetic bug here would corrupt the one dataset that
cannot be regenerated by re-running anything.
"""

from __future__ import annotations

from datetime import date

import pytest

from argus.contracts.provenance import Arm, RunProvenance
from argus.contracts.quant import SubSegment
from argus.contracts.recommendation import (Direction, Levels, Recommendation,
                                            Scenario, ScenarioKind)
from argus.journal.repository import Journal


def _rec(ticker="NVDA", direction=Direction.LONG, chosen=ScenarioKind.BASE,
         entry=100.0, target=115.0, invalidation=92.0) -> Recommendation:
    levels = Levels(entry=entry, target=target, invalidation=invalidation)
    return Recommendation(
        ticker=ticker, sub_segment=SubSegment.FABLESS, as_of=date(2026, 1, 5),
        direction=direction, conviction=0.6,
        scenarios=[
            Scenario(kind=ScenarioKind.BULL, thesis="upside case", probability=0.25,
                     levels=levels),
            Scenario(kind=ScenarioKind.BASE, thesis="base case", probability=0.5,
                     levels=levels),
            Scenario(kind=ScenarioKind.BEAR, thesis="downside case", probability=0.25,
                     levels=Levels(entry=entry, target=entry * 0.85,
                                  invalidation=entry * 1.05)),
        ],
        chosen=chosen, target_holding_days=10, summary="test recommendation",
    )


def _prov(arm=Arm.HUMAN) -> RunProvenance:
    return RunProvenance(arm=arm, corpus_manifest_sha256="deadbeef",
                         corpus_cutoff="2025-12-31")


@pytest.fixture
def journal(tmp_path) -> Journal:
    return Journal(dsn=str(tmp_path / "journal.sqlite"))


def test_open_trade_round_trips(journal):
    trade_id = journal.open_trade(_rec(), _prov(), entry_price=101.5)
    open_trades = journal.open_trades()
    assert len(open_trades) == 1
    assert open_trades[0].id == trade_id
    assert open_trades[0].ticker == "NVDA"
    assert open_trades[0].is_open


def test_flat_recommendation_cannot_be_opened(journal):
    flat = _rec(direction=Direction.FLAT)
    with pytest.raises(ValueError):
        journal.open_trade(flat, _prov(), entry_price=101.5)


def test_close_trade_computes_relative_return(journal):
    trade_id = journal.open_trade(_rec(entry=100.0), _prov(), entry_price=100.0)
    journal.close_trade(trade_id, date(2026, 1, 15), exit_price=110.0,
                        exit_reason="target", benchmark_return=0.03)
    closed = journal.closed_trades()
    assert len(closed) == 1
    # raw = 110/100 - 1 = 0.10; rel = 0.10 - 0.03 = 0.07
    assert closed[0].realized_rel_return == pytest.approx(0.07)


def test_close_trade_short_direction_inverts_return(journal):
    trade_id = journal.open_trade(
        _rec(direction=Direction.SHORT, entry=100.0, target=85.0, invalidation=108.0),
        _prov(), entry_price=100.0)
    journal.close_trade(trade_id, date(2026, 1, 15), exit_price=90.0,
                        exit_reason="target", benchmark_return=0.0)
    closed = journal.closed_trades()
    # price fell 10%; a short profits, so relative return must be positive
    assert closed[0].realized_rel_return == pytest.approx(0.10)


def test_close_unknown_trade_raises(journal):
    with pytest.raises(KeyError):
        journal.close_trade(9999, date(2026, 1, 15), exit_price=100.0,
                            exit_reason="target")


def test_open_trades_excludes_closed(journal):
    t1 = journal.open_trade(_rec(ticker="NVDA"), _prov(), entry_price=100.0)
    journal.open_trade(_rec(ticker="AMD"), _prov(), entry_price=50.0)
    journal.close_trade(t1, date(2026, 1, 10), exit_price=105.0, exit_reason="time")

    open_trades = journal.open_trades()
    assert [t.ticker for t in open_trades] == ["AMD"]
    assert [t.ticker for t in journal.closed_trades()] == ["NVDA"]


def test_record_recommendation_stores_non_trades_too(journal):
    flat = _rec(direction=Direction.FLAT)
    rec_id = journal.record_recommendation(flat, _prov())
    assert rec_id > 0
    # Non-trades are not in the trades table -- they exist for calibration denominator
    # purposes only (handoff: "a model measured only on trades taken looks better than
    # it is").
    assert journal.open_trades() == []


def test_performance_by_arm_separates_arms(journal):
    t1 = journal.open_trade(_rec(ticker="NVDA"), _prov(arm=Arm.HUMAN), entry_price=100.0)
    t2 = journal.open_trade(_rec(ticker="AMD"), _prov(arm=Arm.QUANT_ONLY), entry_price=50.0)
    journal.close_trade(t1, date(2026, 1, 10), exit_price=110.0, exit_reason="target",
                        benchmark_return=0.0)
    journal.close_trade(t2, date(2026, 1, 10), exit_price=45.0, exit_reason="invalidation",
                        benchmark_return=0.0)

    perf = journal.performance_by_arm()
    assert perf["human"]["n_trades"] == 1
    assert perf["human"]["hit_rate"] == 1.0
    assert perf["quant_only"]["n_trades"] == 1
    assert perf["quant_only"]["hit_rate"] == 0.0


def test_performance_by_arm_empty_when_nothing_closed(journal):
    journal.open_trade(_rec(), _prov(), entry_price=100.0)
    assert journal.performance_by_arm() == {}


def test_provenance_persisted_on_trade(journal):
    prov = _prov(arm=Arm.HUMAN)
    trade_id = journal.open_trade(_rec(), prov, entry_price=100.0)
    with journal._conn() as c:
        row = c.execute("SELECT arm, corpus_manifest_sha256, corpus_cutoff FROM trades "
                        "WHERE id = ?", (trade_id,)).fetchone()
    assert row[0] == "human"
    assert row[1] == "deadbeef"
    assert row[2] == "2025-12-31"


def test_sqlite_dsn_is_default_and_creates_parent_dir(tmp_path):
    dsn = tmp_path / "nested" / "journal.sqlite"
    j = Journal(dsn=str(dsn))
    assert dsn.parent.exists()
    assert not j.is_postgres


def test_postgres_dsn_detected_without_connecting():
    j = Journal.__new__(Journal)
    j.dsn = "postgresql://user@host/db"
    j.is_postgres = j.dsn.startswith(("postgres://", "postgresql://"))
    assert j.is_postgres
